//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeliveryAppEntities : DbContext
    {
        public DeliveryAppEntities()
            : base("name=DeliveryAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<order_item> order_item { get; set; }
        public virtual DbSet<order_status> order_status { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_types> product_types { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
